### ISSUE TITLE
not implemented yet

### ISSUE THREAD

**Issue by brightersun99** [thexhr/xodo#1]
Following your tutorial on using this script, I am met with this error.

doas /usr/local/bin/xodo.sh --setup /usr/local/bin/firefox-esr --as firefox --for spinner
doas (staff_test@88typenoob.home) password: 
Setup /usr/local/bin/firefox-esr as firefox for spinner
Not implemented yet

spinner being my user and firefox-esr being my browser

i followed your tutorial here: https://xosc.org/sandbox.html
which i guess is probably outdated now

**Comment by brightersun99** [comment]
doas /usr/local/bin/xodo.sh --setup firefox-esr
Setup /usr/local/bin/firefox-esr as root-firefox-esr for root
Not implemented yet

this also does not work

**Comment by thexhr** [comment]
Seems I didn't had the latest upstream version in the repo. I synced it now, please test again

**Comment by brightersun99** [comment]
works now, thank you sir

**Comment by brightersun99** [comment]
you're the man
