### ISSUE TITLE
/dev/dri/{card0,renderD128}

### ISSUE THREAD

**Issue by gonzalo-** [thexhr/xodo#2]
Hi!

I am doing something like this too, but by hand, I noticed that I need permissions over /dev/dri/card0 & /dev/dri/renderD128 to get acceleration with that "browser" user, so in my case I created a group for my own user and for my browser's user to be able to access those devices, so basically I do the follow:

```
$ doas groupadd _dri
$ usermod -G _dri gonzalo && usermod -G _dri _browser
$ chown gonzalo:_dri /dev/dri/card0
$ chown gonzalo:_dri /dev/dri/renderD128
$ chmod 660 /dev/dri/card0 /dev/dri/renderD128
```

Did you try this? do you think it worth to add it to xodo?

Cheers.-

**Comment by thexhr** [comment]
Hi,

yes, I tried something like this before. After that I started using fbtab(5) to give permissions to drm files.

These days, I don't use xodo any longer due to pledge and unveil's progress,

If you want to submit a patch to implement the above, sure I am happy to integrate it.

Cheers

**Comment by gonzalo-** [comment]
Nah, my fix was kinda ugly to add to xodo, I just have a Makefie with the steps, and as you said, we already have some security methods that fix that already.

Thanks!
